import { asyncHandler } from "../utils/asyncHandler.js";
import { ApiError } from "../utils/ApiError.js";
import { ApiResponse } from "../utils/ApiResponse.js";
import { Survey } from "../models/surveySchema.js";
import { createNotification } from "./notificationController.js";

function toMap(obj) {
  return new Map(Object.entries(obj));
}

export const getSurveyById = asyncHandler(async (req, res) => {
  const { survey_id } = req.params;

  if (!survey_id) {
    throw new ApiError(400, "Survey id is required");
  }

  const survey = await Survey.findOne({ surveyId: survey_id });

  if (!survey) {
    throw new ApiError(404, "Survey not found");
  }

  return res
    .status(200)
    .json(new ApiResponse(200, survey, "Successfully fetched survey"));
});

export const createSurvey = asyncHandler(async (req, res) => {
  const {
    surveyId,
    name,
    status,
    supportedLanguages,
    questionSections,
    categories,
    createdBy,
  } = req.body;

  if (!name || !status || !createdBy || !surveyId) {
    throw new ApiError(
      400,
      "name, status, surveyId and createdBy are required",
    );
  }

  if (!Array.isArray(supportedLanguages) || supportedLanguages.length === 0) {
    throw new ApiError(400, "supportedLanguages must be a non-empty array");
  }

  if (!Array.isArray(questionSections) || questionSections.length === 0) {
    throw new ApiError(400, "Survey must contain at least one questionSection");
  }

  if (!Array.isArray(categories) || categories.length === 0) {
    throw new ApiError(400, "categories must be a non-empty array");
  }

  const normalizedSections = questionSections.map((section) => ({
    ...section,
    questions: section.questions.map((q) => ({
      ...q,
      text: q.text ? toMap(q.text) : undefined,
      audio: q.audio ? toMap(q.audio) : undefined,
      options: q.options?.map((opt) => ({
        ...opt,
        label: opt.label ? toMap(opt.label) : undefined,
      })),
    })),
  }));

  const survey = await Survey.create({
    surveyId,
    name,
    status,
    supportedLanguages,
    questionSections: normalizedSections,
    categories,
    createdBy,
  });

  const userContext = req.user
    ? `${req.user.role.toUpperCase()} (${req.user.email})`
    : "A user";
  await createNotification({
    targetRoles: ["sdrd", "admin"],
    title: "New Survey Created",
    message: `Survey '${name}' was successfully generated by ${userContext}.`,
    type: "SURVEY_CREATED",
    metadata: { surveyId, createdBy },
  });

  return res
    .status(201)
    .json(new ApiResponse(201, survey, "Survey created successfully"));
});

export const getAllSurveys = asyncHandler(async (req, res) => {
  const { status, accessType } = req.query;
  const filters = {};

  if (status) {
    if (Array.isArray(status)) {
      filters.status = { $in: status };
    } else if (status.includes(",")) {
      filters.status = { $in: status.split(",") };
    } else {
      filters.status = status;
    }
  }

  if (accessType) filters.accessType = accessType;

  const surveys = await Survey.find(filters).select(
    "name surveyId status questionSections supportedLanguages accessType allowedChannels createdAt",
  );

  return res
    .status(200)
    .json(new ApiResponse(200, surveys, "Successfully fetched surveys"));
});

export const updateSurvey = asyncHandler(async (req, res) => {
  const { survey_id } = req.params;

  if (!survey_id) {
    throw new ApiError(400, "Survey id is required");
  }

  const existingSurvey = await Survey.findOne({ surveyId: survey_id });

  if (!existingSurvey) {
    throw new ApiError(404, "Survey not found");
  }

  const updates = req.body;
  if (
    (updates.status === "active" || updates.status === "complete") &&
    !existingSurvey.accessType
  ) {
    throw new ApiError(
      400,
      "Active or completed surveys cannot be created without targeted Audience",
    );
  }

  if (
    existingSurvey.status === "active" ||
    existingSurvey.status === "complete"
  ) {
    const allowedKeys = ["allowedChannels", "status"];
    const updateKeys = Object.keys(updates);
    const hasDisallowedUpdates = updateKeys.some(
      (key) => !allowedKeys.includes(key),
    );
    if (hasDisallowedUpdates) {
      throw new ApiError(
        400,
        "Active or completed surveys cannot have accessType, questions or config edited",
      );
    }
  }

  if (updates.questionSections) {
    if (
      !Array.isArray(updates.questionSections) ||
      updates.questionSections.length === 0
    ) {
      throw new ApiError(400, "questionSections must be a non-empty array");
    }

    updates.questionSections = updates.questionSections.map((section) => ({
      ...section,
      questions: section.questions?.map((q) => ({
        ...q,
        text: q.text ? toMap(q.text) : undefined,
        audio: q.audio ? toMap(q.audio) : undefined,
        options: q.options?.map((opt) => ({
          ...opt,
          label: opt.label ? toMap(opt.label) : undefined,
        })),
      })),
    }));
  }

  const survey = await Survey.findOneAndUpdate(
    { surveyId: survey_id },
    { $set: updates },
    { returnDocument: "after", runValidators: true },
  );

  if (!survey) {
    throw new ApiError(404, "Survey not found");
  }

  // Trigger notification if status changed to complete or approved
  if (updates.status && updates.status !== existingSurvey.status) {
    await createNotification({
      targetRoles: ["sdrd", "admin", "fod"],
      title: `Survey ${updates.status.toUpperCase()}`,
      message: `Survey '${survey.name}' status has been updated to ${updates.status}.`,
      type: "SURVEY_STATUS_UPDATE",
      metadata: { surveyId: survey.surveyId },
    });
  }

  return res
    .status(200)
    .json(new ApiResponse(200, survey, "Survey updated successfully"));
});

export const deleteSurvey = asyncHandler(async (req, res) => {
  const { survey_id } = req.params;

  if (!survey_id) {
    throw new ApiError(400, "Survey id is required");
  }

  const survey = await Survey.findOneAndDelete({ surveyId: survey_id });

  if (survey) {
    const userContext = req.user
      ? `${req.user.role.toUpperCase()} (${req.user.email})`
      : "A user";
    await createNotification({
      targetRoles: ["sdrd", "admin"],
      title: "Survey Deleted",
      message: `Survey '${survey.name}' was successfully deleted by ${userContext}.`,
      type: "SURVEY_DELETED",
      metadata: { surveyId: survey_id },
    });
  }

  return res
    .status(200)
    .json(new ApiResponse(200, {}, "Survey deleted successfully"));
});
